template-file-path: root-stack.yaml
parameters:
  GithubOrg: wodoame
  GithubAppRepo: BEM15-rds-app
  Environment: production
  TemplatesBucketName: bem15-rds-infra-stacks
tags:
  Project: bem15-todo-app
  ManagedBy: CloudFormation
  Environment: production
